actions:
  metadata:
    name: ibmCommonServiceOperatorSetup
    description: The actions required to install common service operator
  actionDefs:
    installOperator:
      metadata:
        name: "installOperator"
        description: "install the common service operator"
        case.launcher.type: "script"
        case.cli.alias: "install-operator"
        case.launcher.isdefault: true
      roles:
        - clusterAdmin

      # User must have the ability to create cluster roles and custom resource definitions
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: '*'
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: v1beta1
          - ifExpression:
              "/prereqs/k8sDistros/openshift"
            rule:
              group: security.openshift.io
              resource: securitycontextconstraints
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update

    installOperatorNative:
      metadata:
        name: "installOperatorNative"
        description: "Installs the common service operator by applying k8s manifests"
        case.launcher.type: "script"
        case.cli.alias: "install-operator-native"
      roles:
        - clusterAdmin
      # must be iks, icp or ocp AND Kubernetes 1.11.0 or later running on amd64 Linux
      requires:
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sResources/workerIntelLinux"
          - or:
              - "/case/prereqs/k8sDistros/ibmCloud"
              - "/case/prereqs/k8sDistros/openshift"
      # User must have the ability to create cluster roles and custom resource definitions
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: '*'
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: v1beta1
          # Resolve this permission check ONLY if the prereq resolves to true.
          - ifExpression:
              "!":
                - "/case/prereqs/k8sDistros/openshift"
            rule:
              group: policy
              resource: podsecuritypolicies
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
          - ifExpression:
              "/prereqs/k8sDistros/openshift"
            rule:
              group: security.openshift.io
              resource: securitycontextconstraints
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update

    uninstallOperator:
      metadata :
        name: "uninstallOperator"
        description: "uninstall the common service operator"
        case.launcher.type: "script"
        case.cli.alias: "uninstall-operator"
      roles:
        - clusterAdmin
      # must be iks, icp or ocp AND Kubernetes 1.11.0 or later running on amd64 Linux
      requires:
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sResources/workerIntelLinux"
          - or:
              - "/case/prereqs/k8sDistros/ibmCloud"
              - "/case/prereqs/k8sDistros/ibmCloudPrivate"
              - "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - '*'
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - '*'

    uninstallOperatorNative:
      metadata :
        name: "uninstallOperatorNative"
        description: "uninstall the common service operator"
        case.launcher.type: "script"
        case.cli.alias: "uninstall-operator-native"
      roles:
        - clusterAdmin
      # must be iks, icp or ocp AND Kubernetes 1.11.0 or later running on amd64 Linux
      requires:
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sResources/workerIntelLinux"
          - or:
              - "/case/prereqs/k8sDistros/ibmCloud"
              - "/case/prereqs/k8sDistros/ibmCloudPrivate"
              - "/case/prereqs/k8sDistros/openshift"
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - '*'
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - '*'

    # actions related to catalog
    installCatalog:
      metadata:
        name: "installCatalog"
        description: "install the common service operator catalog"
        case.launcher.type: "script"
        case.cli.alias: "install-catalog"
      roles:
        - clusterAdmin
      k8sPermissions:
        rules: []

    uninstallCatalog:
      metadata:
        name: "uninstallCatalog"
        description: "uninstall the common service operator catalog"
        case.launcher.type: "script"
        case.cli.alias: "uninstall-catalog"
      roles:
        - clusterAdmin
      requires:
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sResources/workerIntelLinux"
          - "/case/prereqs/k8sDistros/openshift"
          - "/case/prereqs/client/cloudctl"
      k8sPermissions:
        rules: []

    # actions related to airgap
    configureCredsAirgap:
      metadata:
        name: "configureCredsAirgap"
        description: "configures login credentails for an image registry"
        case.launcher.type: "script"
        case.cli.alias: "configure-creds-airgap"
      roles:
        - clusterAdmin
      k8sPermissions:
        rules: []

    configureClusterAirgap:
      metadata:
        name: "configureClusterAirgap"
        description: "configures global pullsecret and imagesourcecontentpolicy"
        case.launcher.type: "script"
        case.cli.alias: "configure-cluster-airgap"
      roles:
        - clusterAdmin
      k8sPermissions:
        rules: []

    mirrorImages:
      metadata:
        name: "mirrorImages"
        description: "Mirrors the images to a local registry using oc"
        case.launcher.type: "script"
        case.cli.alias: "mirror-images"
      roles:
        - clusterAdmin
      requires: "/case/prereqs/client/oc"
      k8sPermissions:
        rules:
          - rule:
              group: secrets
              resource: '*'
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update