actions:
  metadata:
    name: ibmServiceability
    description: The actions required to install Serviceability Pod
  actionDefs:
    installServiceability:
      metadata:
        name: "installServiceability"
        description: "Install CloudPak Serviceability Pod"
        case.launcher.type: "script"
        case.cli.alias: "install-serviceability"
      roles: 
      - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
             Please check the CASE prerequisites to validate client machine has the minimum requirements for cli tools and openshift,kubernetes distros  
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - "/case/prereqs/k8sDistros/openshift"
        - "/case/prereqs/client/oc"
      k8sPermissions:
          rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              version: '*'
          - rule: 
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
              version: v1
          - rule: 
              group: ""
              resource: "namespaces"
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
          - rule: 
              group: "extensions"
              resource: "networkpolicies"
              verbs:
              - get
              - list
              - watch
              - create
              - patch
              - update
          - rule: 
              group: ""
              resource: "serviceaccounts"
              verbs:
              - get
              - list
              - watch
              - create
              - patch       
              
    uninstallServiceability:
      metadata:
        name: "uninstallServiceability"
        description: "Uninstalls the Serviceability Pod"
      roles: 
      - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              Please check the CASE prerequisites to validate client machine has the minimum requirements for cli tools and openshift,kubernetes distros
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - "/case/prereqs/k8sDistros/openshift"
        - "/case/prereqs/client/oc"
      k8sPermissions:
        rules:
        - rule:
            group: rbac.authorization.k8s.io
            resource: clusterroles
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update
            version: '*'
        - rule: 
            group: apiextensions.k8s.io
            resource: customresourcedefinitions
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update
            version: v1
        - rule: 
            group: ""
            resource: "namespaces"
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update
        - rule: 
            group: "extensions"
            resource: "networkpolicies"
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update
        - rule: 
            group: ""
            resource: "serviceaccounts"
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update              